"""Add relationship between User and InternalEmail

Revision ID: 01e56fddb0d6
Revises: 5debc5d57b59
Create Date: 2025-07-21 16:16:19.246542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e56fddb0d6'
down_revision: Union[str, Sequence[str], None] = '5debc5d57b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_email', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'internal_email', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internal_email', type_='foreignkey')
    op.drop_column('internal_email', 'user_id')
    # ### end Alembic commands ###
