"""Add SMTP fields to InternalEmail

Revision ID: 03c044fb5137
Revises: 01e56fddb0d6
Create Date: 2025-07-23 08:50:41.107480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c044fb5137'
down_revision: Union[str, Sequence[str], None] = '01e56fddb0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_email', sa.Column('smtp_server', sa.String(length=255), nullable=False, server_default='valor_padrao'))
    op.add_column('internal_email', sa.Column('smtp_port', sa.Integer(), nullable=False, server_default='25'))
    op.add_column('internal_email', sa.Column('smtp_username', sa.String(length=128), nullable=False, server_default='default_username'))
    op.add_column('internal_email', sa.Column('smtp_password', sa.String(length=128), nullable=False, server_default='default_password'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_email', 'smtp_password')
    op.drop_column('internal_email', 'smtp_username')
    op.drop_column('internal_email', 'smtp_port')
    op.drop_column('internal_email', 'smtp_server')
    # ### end Alembic commands ###
