"""Adiciona campo contact_title ao modelo Robot

Revision ID: 0971e267d827
Revises: 222d554351bb
Create Date: 2025-07-21 11:03:50.795051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0971e267d827'
down_revision: Union[str, Sequence[str], None] = '222d554351bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('contact_title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot', 'contact_title')
    # ### end Alembic commands ###
