"""add contact columns

Revision ID: 222d554351bb
Revises: 1f11d23547c6
Create Date: 2025-07-17 10:51:25.429460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '222d554351bb'
down_revision: Union[str, Sequence[str], None] = '1f11d23547c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('titulo', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('nome_congresso', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('ano_congresso', sa.String(length=10), nullable=True))
    op.drop_column('contact', 'data')
    op.alter_column('user', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('contact', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('contact', 'ano_congresso')
    op.drop_column('contact', 'nome_congresso')
    op.drop_column('contact', 'email')
    op.drop_column('contact', 'titulo')
    # ### end Alembic commands ###
