"""Add internal_email to Robot

Revision ID: 5debc5d57b59
Revises: 0971e267d827
Create Date: 2025-07-21 12:32:08.936507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5debc5d57b59'
down_revision: Union[str, Sequence[str], None] = '0971e267d827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('robot', sa.Column('internal_email', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'robot', 'internal_email', ['internal_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robot', type_='foreignkey')
    op.drop_column('robot', 'internal_email')
    op.drop_table('internal_email')
    # ### end Alembic commands ###
