"""Add user_id to Robot

Revision ID: dc4deb65a9a6
Revises: 03c044fb5137
Create Date: 2025-07-23 15:28:54.898798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4deb65a9a6'
down_revision: Union[str, Sequence[str], None] = '03c044fb5137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'robot', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robot', type_='foreignkey')
    op.drop_column('robot', 'user_id')
    # ### end Alembic commands ###
